# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True)),
                ('cost', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'verbose_name': 'Dinner Plan',
                'ordering': ['-end_date'],
                'verbose_name_plural': 'Dinner Plans',
                'get_latest_by': 'end_date',
            },
        ),
        migrations.CreateModel(
            name='DinnerPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('eaten', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='foodplan.DinnerPlan')),
            ],
            options={
                'verbose_name': 'Dinner Plan Item',
                'ordering': ['plan', 'day'],
                'verbose_name_plural': 'Dinner Plan Items',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'ordering': ['title'],
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.AddField(
            model_name='dinnerplanitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='foodplan.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplanitem',
            unique_together=set([('plan', 'day')]),
        ),
    ]
