# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Total cost')),
            ],
            options={
                'verbose_name': 'Dinner Plan',
                'get_latest_by': 'end_date',
                'verbose_name_plural': 'Dinner Plans',
            },
        ),
        migrations.CreateModel(
            name='DinnerPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan.DinnerPlan')),
            ],
            options={
                'verbose_name': 'Dinner Plan Element',
                'ordering': ['day', 'period'],
                'verbose_name_plural': 'Dinner Plan Elements',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'ordering': ['title'],
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.AddField(
            model_name='dinnerplanitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan.Recipe'),
        ),
        migrations.AddField(
            model_name='dinnerplan',
            name='meals',
            field=models.ManyToManyField(through='foodplan.DinnerPlanItem', to='foodplan.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplanitem',
            unique_together=set([('period', 'day')]),
        ),
    ]
