# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekplan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
