# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0002_auto_20160502_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('cost', models.FloatField(blank=True, verbose_name='Total cost')),
            ],
            options={
                'verbose_name_plural': 'Dinner Plans',
                'verbose_name': 'Dinner Plan',
            },
        ),
        migrations.RenameModel(
            old_name='WeekPlanRecipes',
            new_name='DinnerPlanItem',
        ),
        migrations.DeleteModel(
            name='WeekPlan',
        ),
        migrations.AlterModelOptions(
            name='dinnerplanitem',
            options={'ordering': ['week', 'day'], 'verbose_name': 'Dinner Plan Element', 'verbose_name_plural': 'Dinner Plan Elements'},
        ),
        migrations.AlterField(
            model_name='dinnerplanitem',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan.DinnerPlan'),
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplanitem',
            unique_together=set([('week', 'day')]),
        ),
    ]
