# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0003_auto_20160503_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplan',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 3, 18, 59, 17, 395752)),
            preserve_default=False,
        ),
    ]
