# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0004_dinnerplan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplan',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
