# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0005_auto_20160503_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplan',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Total cost'),
        ),
    ]
