# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0006_auto_20160503_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerplanitem',
            options={'ordering': ['day', 'period'], 'verbose_name': 'Dinner Plan Element', 'verbose_name_plural': 'Dinner Plan Elements'},
        ),
        migrations.RenameField(
            model_name='dinnerplanitem',
            old_name='week',
            new_name='period',
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplanitem',
            unique_together=set([('period', 'day')]),
        ),
    ]
