# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0007_auto_20160506_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerplanitem',
            options={'ordering': ['plan', 'day'], 'verbose_name': 'Dinner Plan Item', 'verbose_name_plural': 'Dinner Plan Items'},
        ),
        migrations.AddField(
            model_name='dinnerplan',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dinnerplan',
            name='start_date',
            field=models.DateField(unique=True),
        ),
    ]
