# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0008_auto_20160506_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplanitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='foodplan.Recipe'),
        ),
    ]
