# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0009_auto_20160506_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplan',
            name='cost',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='dinnerplan',
            name='start_date',
            field=models.DateField(unique=True, verbose_name='Start Date'),
        ),
    ]
