# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160427_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='ingress',
            field=models.CharField(default='Temporary', max_length=500),
            preserve_default=False,
        ),
    ]
